import { Fund } from "../types/fundTypes";

export const mockFunds: Fund[] = [
    {
        id: 1,
        nombreFondo: "Fondo Ahorro 1",
        clasificacion: "Renta Fija",
        fecha: "14/05/2024",
        valorMilCuotapartes: 150.25,
        variacionCuotapartePorcentaje: [0.1, 0.15, 0.2, 0.18],
        fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        cantidadCuotapartes: 308205,
        patrimonio: 53717128121.52,
        marketShare: 0.664,
        sociedadDepositaria: "Banco de Galicia y Buenos Aires S.A.",
        codigoCNV: "221",
        calificacion: "AAf.ar",
        codigoCAFCI: "734",
        codigoSocGte: "81",
        codigoSocDep: "2",
        sociedadGerente: "Galicia Asset Management S.A.U.",
        codigoClasificacion: "1",
        codigoMoneda: "ARS",
        codigoRegion: "ARG",
        codigoHorizonte: "Corto Plazo",
        indiceMM: 1,
        comisionIngreso: 0.0000,
        honorariosAdmSG: 2.5075,
        honorariosAdmSD: 0.4425,
        gastosOrdGestion: 0.0000,
        comisionRescate: 0.0000,
        comisionTransferencia: 0.0000,
        honorariosExito: 0.0000,
        monedaFondo: "ARS",
        plazoLiq: "1 día hábil",
        decreto596: "No",
        idFondoCAFCIPadre: "N/A",
        idFondoCNVPadre: "N/A",
        tipoEscision: "N/A",
        repatriacion: "No",
        minimoInversion: 1000,
        actual: 308205.472,
        fechaActual: "13/05/2024",
        variacionPorcentaje: 0.407,
        reexpPesos: 52267355932.21,
    },
    {
        id: 2,
        nombreFondo: "Fondo Renta 2",
        clasificacion: "Renta Variable",
        fecha: "14/05/2024",
        valorMilCuotapartes: 341.119,
        variacionCuotapartePorcentaje: [0.1, 0.2, 0.3, 0.4],
        cantidadCuotapartes: 341119,
        patrimonio: 41526895173.57,
        marketShare: 0.512,
        sociedadDepositaria: "Banco de Galicia y Buenos Aires S.A.",
        codigoCNV: "221",
        calificacion: "AAf.ar",
        codigoCAFCI: "193",
        codigoSocGte: "81",
        codigoSocDep: "2",
        sociedadGerente: "Galicia Asset Management S.A.U.",
        codigoClasificacion: "1",
        codigoMoneda: "ARS",
        codigoRegion: "ARG",
        codigoHorizonte: "Corto Plazo",
        indiceMM: 1,
        comisionIngreso: 0.0000,
        honorariosAdmSG: 2.0400,
        honorariosAdmSD: 0.3600,
        gastosOrdGestion: 0.0000,
        comisionRescate: 0.0000,
        comisionTransferencia: 0.0000,
        honorariosExito: 0.0000,
        monedaFondo: "ARS",
        plazoLiq: "1 día hábil",
        decreto596: "No",
        idFondoCAFCIPadre: "N/A",
        idFondoCNVPadre: "N/A",
        tipoEscision: "N/A",
        repatriacion: "No",
        minimoInversion: 1000,
        actual: 341119.538,
        fechaActual: "13/05/2024",
        variacionPorcentaje: 0.409,
        reexpPesos: 40069295274.68,
        fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    },
    {
        id: 3,
        nombreFondo: "Fondo Renta 3",
        clasificacion: "Renta Variable",
        fecha: "14/05/2024",
        valorMilCuotapartes: 341.119,
        variacionCuotapartePorcentaje: [0.1, 0.2, 0.3, 0.4],
        cantidadCuotapartes: 341119,
        patrimonio: 41526895173.57,
        marketShare: 0.512,
        sociedadDepositaria: "Banco de Galicia y Buenos Aires S.A.",
        codigoCNV: "221",
        calificacion: "AAf.ar",
        codigoCAFCI: "193",
        codigoSocGte: "81",
        codigoSocDep: "2",
        sociedadGerente: "Galicia Asset Management S.A.U.",
        codigoClasificacion: "1",
        codigoMoneda: "ARS",
        codigoRegion: "ARG",
        codigoHorizonte: "Corto Plazo",
        indiceMM: 1,
        comisionIngreso: 0.0000,
        honorariosAdmSG: 2.0400,
        honorariosAdmSD: 0.3600,
        gastosOrdGestion: 0.0000,
        comisionRescate: 0.0000,
        comisionTransferencia: 0.0000,
        honorariosExito: 0.0000,
        monedaFondo: "ARS",
        plazoLiq: "1 día hábil",
        decreto596: "No",
        idFondoCAFCIPadre: "N/A",
        idFondoCNVPadre: "N/A",
        tipoEscision: "N/A",
        repatriacion: "No",
        minimoInversion: 1000,
        actual: 341119.538,
        fechaActual: "13/05/2024",
        variacionPorcentaje: 0.409,
        reexpPesos: 40069295274.68,
        fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    },
    {
        id: 4,
        nombreFondo: "Fondo Renta 4",
        clasificacion: "Renta Variable",
        fecha: "14/05/2024",
        valorMilCuotapartes: 341.119,
        variacionCuotapartePorcentaje: [0.1, 0.2, 0.3, 0.4],
        cantidadCuotapartes: 341119,
        patrimonio: 41526895173.57,
        marketShare: 0.512,
        sociedadDepositaria: "Banco de Galicia y Buenos Aires S.A.",
        codigoCNV: "221",
        calificacion: "AAf.ar",
        codigoCAFCI: "193",
        codigoSocGte: "81",
        codigoSocDep: "2",
        sociedadGerente: "Galicia Asset Management S.A.U.",
        codigoClasificacion: "1",
        codigoMoneda: "ARS",
        codigoRegion: "ARG",
        codigoHorizonte: "Corto Plazo",
        indiceMM: 1,
        comisionIngreso: 0.0000,
        honorariosAdmSG: 2.0400,
        honorariosAdmSD: 0.3600,
        gastosOrdGestion: 0.0000,
        comisionRescate: 0.0000,
        comisionTransferencia: 0.0000,
        honorariosExito: 0.0000,
        monedaFondo: "ARS",
        plazoLiq: "1 día hábil",
        decreto596: "No",
        idFondoCAFCIPadre: "N/A",
        idFondoCNVPadre: "N/A",
        tipoEscision: "N/A",
        repatriacion: "No",
        minimoInversion: 1000,
        actual: 341119.538,
        fechaActual: "13/05/2024",
        variacionPorcentaje: 0.409,
        reexpPesos: 40069295274.68,
        fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    },
    {
        id: 5,
        nombreFondo: "Fondo Renta 5",
        clasificacion: "Renta Variable",
        fecha: "14/05/2024",
        valorMilCuotapartes: 341.119,
        variacionCuotapartePorcentaje: [0.1, 0.2, 0.3, 0.4],
        cantidadCuotapartes: 341119,
        patrimonio: 41526895173.57,
        marketShare: 0.512,
        sociedadDepositaria: "Banco de Galicia y Buenos Aires S.A.",
        codigoCNV: "221",
        calificacion: "AAf.ar",
        codigoCAFCI: "193",
        codigoSocGte: "81",
        codigoSocDep: "2",
        sociedadGerente: "Galicia Asset Management S.A.U.",
        codigoClasificacion: "1",
        codigoMoneda: "ARS",
        codigoRegion: "ARG",
        codigoHorizonte: "Corto Plazo",
        indiceMM: 1,
        comisionIngreso: 0.0000,
        honorariosAdmSG: 2.0400,
        honorariosAdmSD: 0.3600,
        gastosOrdGestion: 0.0000,
        comisionRescate: 0.0000,
        comisionTransferencia: 0.0000,
        honorariosExito: 0.0000,
        monedaFondo: "ARS",
        plazoLiq: "1 día hábil",
        decreto596: "No",
        idFondoCAFCIPadre: "N/A",
        idFondoCNVPadre: "N/A",
        tipoEscision: "N/A",
        repatriacion: "No",
        minimoInversion: 1000,
        actual: 341119.538,
        fechaActual: "13/05/2024",
        variacionPorcentaje: 0.409,
        reexpPesos: 40069295274.68,
        fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    },
];

export const mockFund = {
    fondo: "Fondo Ahorro 1",
    variacionCuotapartePorcentaje: [0.1, 0.2, 0.3, 0.4],
    fechas: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
};
